# [env]
# TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 18

[font.normal]
# family = "VictorMono Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "FiraCode Nerd Font"
# family = "Iosevka Nerd Font"
# family = "MartianMono Nerd Font"
# family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10_000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"

[window]
opacity = 1
decorations = "Buttonless"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
