[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 18
offset.x = 0
offset.y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/local/bin/fish"

[window]
opacity = 1
decorations = "None"
decorations_theme_variant = "Dark"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 0


[colors.primary]
background = "#141414"
foreground = "#ffffff"

[colors.normal]
black = "#000000"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#ffffff"

